### ISSUE TITLE
Sometime the system font not applying to the channel header (font)

### ISSUE THREAD

**Issue by soumyadip69** [OctoGramApp/OctoGram#10]
![Screenshot_20230916-112055_OctoGram](https://github.com/OctoGramApp/OctoGram/assets/80621495/900d3734-f472-4c2b-ac2a-42270fbfba4a)

**Comment by ImOnlyFire** [comment]
Do you have `use system font` enabled in the settings? (octogram settings > appearance > use system font)

**Comment by soumyadip69** [comment]
Yes I've enabled that actually sometimes the system font working & sometimes not

**Comment by null-nick** [comment]
Technically solved in this commit, in the next beta you confirm that it is solved https://github.com/OctoGramApp/OctoGram/commit/e7e6b273238df5e2835ba17711792a197aa0d7ee

**Comment by soumyadip69** [comment]
Thanks sir for hard work 🙏🤍
