### ISSUE TITLE
[Bug]: Camera X- recording video using the "lock" feature don't work

### ISSUE THREAD

**Issue by Malachiel87** [OctoGramApp/OctoGram#19]
### Code of Conduct

- [X] I have checked for similar issues and confirmed this is unique
- [X] This issue does not occur in the latest default Telegram client

### Expected Behavior

When using camera x and record something you can't "lock" (i mean pressing the locker icon that show when you record the video. I am using Pixel 7 Pro and android 14
![image](https://github.com/OctoGramApp/OctoGram/assets/3611852/89447324-afc5-4cb2-aa10-431e7598d236)

### Current Behavior

It just do nothing when swipping the finger on the locker icon

### Steps to Reproduce (if applicable)

1. open octogram
2. open the camera (with cameraX enabled)
3. record a video the locker should appaer
4. swipe the finger from the circle to the locker
5. nothing happen

**Comment by null-nick** [comment]
fixed in next release
