### ISSUE TITLE
[Bug]: When a crash report exist, everytime i start octogram it say the app is crashed

### ISSUE THREAD

**Issue by Malachiel87** [OctoGramApp/OctoGram#20]
### Code of Conduct

- [X] I have checked for similar issues and confirmed this is unique
- [X] This issue does not occur in the latest default Telegram client

### Expected Behavior

When you have a crash report stored in octogram, everytime you start the app (killing it or on phone boot) it say is crashed, it was not happening on previous update

### Current Behavior

1. have a

### Steps to Reproduce (if applicable)

1. have a crash report saved
2. kill octogram
3. start octogram
4. see the sad duck saying octogram crashed

### Octogram Crash Log

this "crash" don't generate anything, i believe is something of false positive

**Comment by null-nick** [comment]
fixed
