### ISSUE TITLE
Feature request: Adavance Indicator Status.

### ISSUE THREAD

**Issue by PLAYERUNKNOWNHatsune01** [OctoGramApp/OctoGram#3]
I would like to suggest a feature that Forkgram has that is really nice. The indicator status. Where when your contact was online the indicator will show as the color of your Theme on Telegram, Yellow when it's on recent app, Orange when the user was afk for a while, and Red when the app was on the background. This really helpful for me and I think some would find it helpful too. So I would know what my friends or my family doing (or if they ignoring my message lol). Since the Octogram already give you an option to see who's online on group. I'm pretty sure you guys can implement this very easily! 🌟⭐⭐

**Comment by ImOnlyFire** [comment]
This idea is great, but I find the whole thing a bit privacy invasive for those who don't have our client. The current implementation, while being really simple, is also privacy-respecting for all the users since it only fetches the "online" status of the profile.
