### ISSUE TITLE
[Bug]: Application theme resets to default after entering a chat room with a non-standard theme

### ISSUE THREAD

**Issue by farline99** [OctoGramApp/OctoGram#30]
### Code of Conduct

- [X] I have checked for similar issues and confirmed this is unique
- [X] This issue does not occur in the latest default Telegram client

### Expected Behavior

Application theme stays active after entering chat with custom theme

### Current Behavior

Default theme is chosen automatically

### Additional Information

Happens on Nekogram latest too. But not on official Telegram 10.12.0 client from telegram.org.

Version: 2.1.4 beta

**Comment by null-nick** [comment]
fixed f83e56b
