### ISSUE TITLE
[Bug]: first user-created folder works as "all chats" upon first start

### ISSUE THREAD

**Issue by farline99** [OctoGramApp/OctoGram#31]
### Code of Conduct

- [X] I have checked for similar issues and confirmed this is unique
- [X] This issue does not occur in the latest default Telegram client

### Expected Behavior

It shows only folder's chats, not all.

### Current Behavior

All chats folder is disabled. Now default folder is created by me. And after removing app from recent and going into it again this folder shows all chats/channels/bots. After switching between folders it behaves as expected.

### Additional Information

Version: 2.1.4 beta

**Comment by null-nick** [comment]
@farline99 premium user or not?

**Comment by farline99** [comment]
@null-nick yes, i'm a premium user.
