### ISSUE TITLE
[Bug]: doesn't pass play protect anymore 

### ISSUE THREAD

**Issue by stignarnia** [OctoGramApp/OctoGram#34]
### Code of Conduct

- [X] I have checked for similar issues and confirmed this is unique
- [X] This issue does not occur in the latest default Telegram client

### Expected Behavior

It used to install without issue up until two versions ago

### Current Behavior

Play protect says it might be dangerous

**Comment by null-nick** [comment]
@stignarnia false positive, gplay protect issue + https://t.me/OctoGramChat/18642

**Comment by stignarnia** [comment]
Yes yes never wanted to imply that google was right, still it's a "bug" in the sense that it might scare people off and should be fixed, if possible
